### ISSUE TITLE
Create user settings page

### ISSUE THREAD

**Issue by 0x213F** [0x213F/jukebox-radio-react#1]
**Summary**

There needs to be a page for user settings. The main motivation for this is creating an interface so the user can sync their Spotify account with JR.

**Implementation requirements**

- The new page may be accessed from the left bar. It could go either at the bottom or right below login.
- Once clicking the link in the left bar, the URL changes to `/settings`
- Once in settings, [get user settings via the JR Django endpoint](https://github.com/0x213F/jukebox-radio-django/pull/3).
- If the API response has a non-null value for the Spotify access token, then display a checked checkbox. If the value is null, display an unchecked checkbox.
  - `[  ] Spotify`
  - `[x] Spotify`
- The "Spotify" text should be a link. When clicked, it should open the "authorizationUrl" (from the user settings API) in a new tab.

**Comment by 0x213F** [comment]
One more thing you might need to do in your Spotify developer account. You need to configure a "Redirect URI" as follows:

<img width="614" alt="Screen Shot 2021-01-13 at 5 52 42 PM" src="https://user-images.githubusercontent.com/14227976/104533928-26efc500-55c8-11eb-8352-b593ec494dee.png">

To get here, you will need to log into you Spotify developer account, select your project, and click the green button in the upper right with the settings icon that reads "Edit Settings." Copy and paste the following into the box, click "Add" then "Save." Open the settings menu once more to verify that it saved as expected.

`http://localhost:3000/users/user/connect-spotify/`

**Comment by 0x213F** [comment]
You should call the endpoint when the page is loaded. if you look in `App.js` you'll see a bunch of comments one after another

```
// verify authentication
// load stream
// load queue
// load comments
// load voice recordings
```

You'll want to add one more to the end, which will be `// get user settings`. You can model this after the other ones.

You will need to update the Redux reducer so it properly stores the user settings data.

Afterwards, you will need to connect your `UserSettings` component to Redux. Then connect state to props. You can see an example of that at the bottom of `Chat.js`. Now that you have user settings data bound to the props of `UserSettings`, you can render what is needed (see top of this issue) inside the render method.

**Comment by op1346** [comment]
https://github.com/0x213F/jukebox-radio-react/pull/3
